name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install tools
      run: sudo apt-get install -y clang ninja-build
    - name: configure
      run: mkdir build
    - name: cmake
      run: (cd build && cmake ..)
    - name: build
      run: (cd build && cmake --build .)

