name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install tools
      run: sudo apt-get install -y clang ninja-build build-essential make
    - name: Restore artifacts, or setup vcpkg (do not install any package)
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgDirectory: '/usr/local/vcpkg'
        runVcpkgInstall: true
        vcpkgJsonGlob: 'vcpkg.json'
        appendedCacheKey: vcpkginstall
    - name: configure
      run: mkdir build
    - name: cmake
      run: (cd build && cmake -GNinja ..)
    - name: build
      run: (cd build && cmake --build .)

